framework:
    messenger:
        failure_transport: failed
#        serializer:
#            default_serializer: messenger.transport.symfony_serializer
        default_bus: bus_commands

        buses:
            bus_commands:
                middleware:
                - 'App\Middleware\AuditMiddleware'

            bus_events:
                middleware:
                - 'App\Middleware\AcceptNoHandlerMiddleware'

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            async: '%env(MESSENGER_TRANSPORT_DSN)%'
            priority_async: '%env(MESSENGER_TRANSPORT_PRIORITY_DSN)%'
            failed: 'doctrine://default?queue_name=failed'
            my_api:
                dsn: https://enp0dpegm2zx.x.pipedream.net
                serializer: messenger.transport.symfony_serializer

            # sync: 'sync://'

        routing:
            # Route your messages to the transports
            'App\Message\PersonYouSawWasNegative': [ async, priority_async ]
            'App\Message\PersonYouSawWasPositive': [ priority_async, my_api ]
